### ISSUE TITLE
Private IP address disclosed

### ISSUE THREAD

**Issue by yashcho** [SeleniumHQ/selenium-assistant#10]
## 🐛 Bug Report

Hello Team,

Summary:
When we done some security pen-testing of open-source selenium version 3.141.59 installed on our project application, we got the Private IP address disclosed in selenium URL endpoint(/grid/console), Discovering the private addresses used within an organization can help an attacker in carrying out network-layer attacks aiming to penetrate the organization's internal infrastructure.

As you can see in this screenshot:
![image](https://user-images.githubusercontent.com/69308923/89651733-fb163800-d8e1-11ea-97c0-9f986edcfc2c.png)

I believe this is a low level severity bug but if you can provide us some fix on it would appreciate it?

**Comment by diemol** [comment]
@yashcho this is not the repository for Selenium bugs. 

In addition, the issues get closed in the Selenium repository because you are deleting the template. Also, seems you are using Grid 3.x, which is not under development anymore. You can use Grid 4.x, on alpha status as I write this, and raise a PR is necessary, you can download it here https://www.selenium.dev/downloads/.
