### ISSUE TITLE
C# Webdriver doesn't see new tab from link

### ISSUE THREAD

**Issue by MESWEB** [SeleniumHQ/selenium-assistant#5]
## 🐛 Bug Report

Driver.Firefox

I have 2 tabs already opened and after when link blank target is opened and new tab show then Webdriver doesn't see content from this tab.

## To Reproduce

Before you start open 2 tabs using webdriver and click link with target blank values.

## Expected behavior

Webdriver should automatic focus on this tab.

**Comment by diemol** [comment]
💬 It looks like this is a question rather than an issue.
  💡 A better way to address this is:
  * 📫 Send questions and support requests to the [Selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
  * 📮 Post them to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium)
  * 🗣 Join us in the [IRC/Slack channel](https://seleniumhq.herokuapp.com/) where the community can help you as well
